# Generated by Django 4.2.5 on 2023-12-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='price',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='product_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
