# Generated by Django 4.2.5 on 2024-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_name',
            field=models.TextField(blank=True, null=True, verbose_name='Имя файла'),
        ),
    ]
